### ISSUE TITLE
Review for Bioconda recipe

### ISSUE THREAD

**Issue by marcelm** [LanLab/salty#1]
Hi, I was looking at your [Bioconda recipe PR](https://github.com/bioconda/bioconda-recipes/pull/39104) for this package and noticed a couple of minor things not directly related to the recipe, but to the tool, which I wanted to list here.

- Running `python setup.py install` to install a package [is deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). You should change the installation instructions to use `pip install .` instead (use `pip install -e .` during development for an editable install).
- The README refers to running salty via `python salty.py`, but this works only if run from the `salty/` subdirectory. You specified in `setup.py` that a `salty` binary is to be installed, and that is also what the Bioconda recipe tests. I suggest to use just `salty` for consistency.
- Since this is a pure Python package (no extension modules), you could switch to using `pyproject.toml` for declaring project metadata and get rid of `setup.py` entirely. See [this example](https://github.com/marcelm/cutadapt/blob/main/pyproject.toml). This is the modern way to do packaging. :smile:
- Your Conda installation instructions may work, but note that this is not generally the case as the [Bioconda setup instructions](http://bioconda.github.io/) want you to also specify strict channel order. Also, the channel order is different, so in general, the options would be `-c conda-forge -c bioconda --strict-channel-priority`.

**Comment by marcelm** [comment]
One more point: It would be good to state the license explicitly. There is a LICENSE file with the GPL 3, but some projects use "GPL 3 or later" and some use "GPL 3 only". (There are two different [SPDX license identifiers](https://spdx.org/licenses/) "GPL-3.0-only" and "GPL-3.0-or-later".)

Note that using the GPL may mean that some people may refrain from using your software as it has a "viral" aspect. (As derived works also need to be licensed under the GPL 3.) You could choose a simple permissive license such as [the MIT license](https://choosealicense.com/licenses/mit/) to avoid this. If you’re aware of this aspect, please don’t see this as criticism of your choice of license; I just wanted to point out what it means in case you were not aware of the implications.

**Comment by liamcheney** [comment]
Hey @marcelm, 
Thanks for going over salty. Regarding the license we are happy to keep the existing language. Thanks for checking. All the other comments have been addressed.
Cheers,
Liam

**Comment by marcelm** [comment]
Great! Nice I was able to help.
