### ISSUE TITLE
Outputs version number and nothing else

### ISSUE THREAD

**Issue by VishnuRaghuram94** [LanLab/salty#3]
Hello,

Thank you for developing this tool. I installed it using the conda commad 
`conda install -c conda-forge -c bioconda salty`

And ran it using
`salty --input_folder fastas_dir/ --output_folder salty_outputs/`

and the output is simply 
`salty version: 1.1.0`

No files are being written. `salty -h` functions as expected and `salty -v` reports 1.1.0 . 
Could you please advise? 

Thank you!
Vishnu

**Comment by liamcheney** [comment]
Hello @VishnuRaghuram94,

Thank you for brining this to my attention. I have updated SaLTy and the changes are now available through Conda.

You can upgrade SaLTy through EITHER of the following:

    - conda upgrade salty #(if already installed)
    OR
    - conda install -c bioconda salty==1.0.4

If you have any further issues please let me know.

Cheers,
Liam

**Comment by VishnuRaghuram94** [comment]
It runs now, thank you!
